apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTE: do not set `namespace:` here.
# The namespace is owned by the ApplicationSet destination ([overlay]-[app]).

labels:
  - pairs:
      environment: dev
    # keep selectors stable; label pods too
    includeSelectors: false
    includeTemplates: true

resources:
  - ../../base

replicas:
  - name: whoami
    count: 1
